[package]
name = "tasker_model"
version.workspace = true
edition.workspace = true

[lib]
crate-type = [ "cdylib", "rlib" ]

[dependencies]
serde.workspace = true
hdi.workspace = true
membranes_types = {path = "../../../crates/membranes_types" }