[package]
name = "agent_directory_integrity"
version = "0.1.0-hdk.154"
edition = "2021"

[lib]
crate-type = [ "cdylib", "rlib" ]

[dependencies]
serde = { version = "1.0", default-features = false }

hdi = { version = "0.1.3", default-features = false }
