[package]
edition = "2021"
name = "agent_directory_integrity"
version = "0.0.1"

[lib]
crate-type = ["cdylib", "rlib"]


[dependencies]
agent_directory_integrity_zome = {git = "https://github.com/ddd-mtl/agent-directory-zome", package = "agent_directory_integrity"}
hdi.workspace = true