[workspace]
resolver = "2"
members = [
  # Membranes Zome
  "crates/membranes_types",
  "crates/membranes_integrity",
  "crates/membranes",
  # Threshold Plugins
  "crates/threshold_CreateEntryCount_types",
  "crates/threshold_CreateEntryCount_integrity",
  "crates/threshold_CreateEntryCount",
  "crates/threshold_Vouch_types",
  "crates/threshold_Vouch_integrity",
  "crates/threshold_Vouch",
  "crates/threshold_Progenitor",
  "crates/threshold_Progenitor_integrity",
  "crates/threshold_Progenitor_types",
  # Playground
  "playground/zomes/tasker_model",
  "playground/zomes/tasker",
  "playground/zomes/agent_directory",
  "playground/zomes/agent_directory_integrity",
  #"sweettest",
]

[workspace.package]
version = "0.506.0"
rust-version = "1.75.0"
edition = "2021"

[workspace.dependencies]
serde = { version = "=1.0.219", default-features = false }
holochain_serialized_bytes = "=0.0.56"
hdi = { version = "=0.7.0-dev.18", default-features = false }
hdk = { version = "=0.6.0-dev.21", default-features = false }

zome_utils = { git = "https://github.com/ddd-mtl/zome-utils", branch = "hdk-6.0" }

[profile.dev]
lto = false
opt-level = 0
overflow-checks = false

[profile.release]
opt-level = "z"
lto = true

[profile.release.build-override]
opt-level = "z"
