[workspace]
resolver = "2"
members = [
  "crates/membranes_types",
  "crates/membranes_integrity",
  "crates/membranes",
  "playground/zomes/tasker",
  "playground/zomes/tasker_model",
  "playground/zomes/agent_directory",
  "playground/zomes/agent_directory_integrity",
  #"sweettest",
]

[profile.dev]
lto = false
opt-level = 0
overflow-checks = false

[profile.release]
opt-level = "z"
lto = true

[profile.release.build-override]
opt-level = "z"
