/* This file is generated by zits. Do not edit manually */

import {CREATE_ENTRY_COUNT_THRESHOLD_NAME, CrudType, CreateEntryCountThresholdEntry, ThresholdType, MembraneCrossedClaim, RoleClaim, MembraneRole, Membrane, SignedActionHash, MembraneThreshold, ThresholdReachedProof, Privilege, HasRoleInput, ClaimRoleInput, MembraneInput, ClaimThresholdInput, MyAppEntryType, CreateEntryCountThreshold, GetCreateCountInput, } from './createEntryCount.types';
import {
/** types.ts */
HoloHash,
AgentPubKey,
DnaHash,
WasmHash,
EntryHash,
ActionHash,
AnyDhtHash,
ExternalHash,
KitsuneAgent,
KitsuneSpace,
HoloHashB64,
AgentPubKeyB64,
DnaHashB64,
WasmHashB64,
EntryHashB64,
ActionHashB64,
AnyDhtHashB64,
InstalledAppId,
Signature,
CellId,
DnaProperties,
RoleName,
InstalledCell,
Timestamp,
Duration,
HoloHashed,
NetworkInfo,
FetchPoolInfo,
/** hdk/action.ts */
SignedActionHashed,
ActionHashed,
ActionType,
Action,
NewEntryAction,
Dna,
AgentValidationPkg,
InitZomesComplete,
CreateLink,
DeleteLink,
OpenChain,
CloseChain,
Update,
Delete,
Create,
/** hdk/capabilities.ts */
CapSecret,
CapClaim,
GrantedFunctionsType,
GrantedFunctions,
ZomeCallCapGrant,
CapAccess,
CapGrant,
///** hdk/countersigning.ts */
//CounterSigningSessionData,
//PreflightRequest,
//CounterSigningSessionTimes,
//ActionBase,
//CounterSigningAgents,
//PreflightBytes,
//Role,
//CountersigningAgentState,
/** hdk/dht-ops.ts */
DhtOpType,
DhtOp,
getDhtOpType,
getDhtOpAction,
getDhtOpEntry,
getDhtOpSignature,
/** hdk/entry.ts */
EntryVisibility,
AppEntryDef,
EntryType,
EntryContent,
Entry,
/** hdk/record.ts */
Record as HcRecord,
RecordEntry as HcRecordEntry,
/** api/admin/types.ts */
InstalledAppInfoStatus,
DeactivationReason,
DisabledAppReason,
StemCell,
ProvisionedCell,
ClonedCell,
CellType,
CellInfo,
AppInfo,
MembraneProof,
FunctionName,
ZomeName,
ZomeDefinition,
IntegrityZome,
CoordinatorZome,
DnaDefinition,
ResourceBytes,
ResourceMap,
CellProvisioningStrategy,
CellProvisioning,
DnaVersionSpec,
DnaVersionFlexible,
AppRoleDnaManifest,
AppRoleManifest,
AppManifest,
AppBundle,
AppBundleSource,
NetworkSeed,
ZomeLocation,
   } from '@holochain/client';

import {
/** Common */
DhtOpHashB64,
DhtOpHash,
/** DnaFile */
DnaFile,
DnaDef,
Zomes,
WasmCode,
/** entry-details */
EntryDetails,
RecordDetails,
Details,
DetailsType,
EntryDhtStatus,
/** Validation */
ValidationStatus,
ValidationReceipt,
   } from '@holochain-open-dev/core-types';

import {ZomeProxy} from '@ddd-qc/lit-happ';
import {createEntryCountFunctionNames} from './createEntryCount.fn';

/**
 *
 */
export class CreateEntryCountProxy extends ZomeProxy {
  static readonly DEFAULT_ZOME_NAME = "zThreshold_CreateEntryCount"
  static readonly FN_NAMES = createEntryCountFunctionNames
 


  async getCreateCount(input: GetCreateCountInput): Promise<number> {
    return this.call('get_create_count', input);
  }

  async publishCreateEntryCountThreshold(th: CreateEntryCountThreshold): Promise<EntryHash> {
    return this.call('publish_CreateEntryCount_threshold', th);
  }

  async getThresholdCreateEntryCount(eh: EntryHash): Promise<CreateEntryCountThreshold | null> {
    return this.call('get_threshold_CreateEntryCount', eh);
  }

  async getAllThresholdsCreateEntryCount(): Promise<CreateEntryCountThreshold[]> {
    return this.call('get_all_thresholds_CreateEntryCount', null);
  }

  async claimThresholdCreateEntryCount(input: ClaimThresholdInput): Promise<ActionHash | null> {
    return this.call('claim_threshold_CreateEntryCount', input);
  }
}
