/* This file is generated by zits. Do not edit manually */

import {
/** Types */
HoloHash,
AgentPubKey,
DnaHash,
WasmHash,
EntryHash,
ActionHash,
AnyDhtHash,
KitsuneAgent,
KitsuneSpace,
InstalledAppId,
Signature,
CellId,
DnaProperties,
RoleId,
InstalledCell,
Timestamp,
HoloHashed,
/** Action */
SignedActionHashed,
ActionHashed,
ActionType,
Action,
NewEntryAction,
Dna,
AgentValidationPkg,
InitZomesComplete,
CreateLink,
DeleteLink,
OpenChain,
CloseChain,
Update,
Delete,
Create,
/** Capabilities */
CapSecret,
CapClaim,
ZomeCallCapGrant,
CapAccess,
CapGrant,
/** CounterSigning */
//CounterSigningSessionData,
//PreflightRequest,
//CounterSigningSessionTimes,
//ActionBase,
//CounterSigningAgents,
//PreflightBytes,
//Role,
//CountersigningAgentState,
/** DhtOps */
DhtOpType,
DhtOp,
getDhtOpType,
getDhtOpAction,
getDhtOpEntry,
getDhtOpSignature,
/** Entry */
EntryVisibility,
AppEntryType,
EntryType,
EntryContent,
Entry,
/** Record */
Record,
RecordEntry,
/** admin types */
ZomeName,
MembraneProof,
ZomeDefinition,
IntegrityZome,
CoordinatorZome,
DnaDefinition,
ResourceBytes,
ResourceMap,
CellProvisioning,
HoloHashB64,
DnaVersionSpec,
DnaVersionFlexible,
NetworkSeed,
ZomeLocation,
   } from '@holochain/client';

import {
// Common
Dictionary,
EntryHashB64,
ActionHashB64,
DhtOpHashB64,
DnaHashB64,
AgentPubKeyB64,
AnyDhtHashB64,
DhtOpHash,
// DnaFile
DnaFile,
DnaDef,
Zomes,
WasmCode,
// entry-details
EntryDetails,
RecordDetails,
Details,
DetailsType,
EntryDhtStatus,
// Validation
ValidationStatus,
ValidationReceipt,
   } from '@holochain-open-dev/core-types';

export interface Vouch {
  subject: AgentPubKey
  forRole: string
}

/**  */
export interface MembraneCrossedClaim {
  proofs: ThresholdReachedProof[]
  membraneEh: EntryHash
  subject: AgentPubKey
}

/**  */
export interface RoleClaim {
  subject: AgentPubKey
  membraneIndex: number
  roleEh: EntryHash
  membraneClaimEh: EntryHash
}

/**  */
export interface MembraneRole {
  name: string
  privileges: Privilege[]
  enteringMembraneEhs: EntryHash[]
}

/**  */
export interface Membrane {
  thresholdEhs: EntryHash[]
}

export enum MembraneThresholdType {
	CreateEntryCount = 'CreateEntryCount',
	Vouch = 'Vouch',
	Progenitor = 'Progenitor',
}
export type MembraneThresholdVariantCreateEntryCount = {createEntryCount: CreateEntryCountThreshold}
export type MembraneThresholdVariantVouch = {vouch: VouchThreshold}
export type MembraneThresholdVariantProgenitor = {progenitor: null}
export type MembraneThreshold = 
 | MembraneThresholdVariantCreateEntryCount | MembraneThresholdVariantVouch | MembraneThresholdVariantProgenitor;

export interface MyAppEntryType {
  id: number
  zomeId: number
  isPublic: boolean
}

export interface CreateEntryCountThreshold {
  entryType: MyAppEntryType
  requiredCount: number
}

export interface VouchThreshold {
  requiredCount: number
  byRole: string
  forRole: string
}

/**  */
export interface ThresholdReachedProof {
  thresholdEh: EntryHash
  signedActions: SignedActionHashed[]
}

export type CrudType =
  | "Create" | "Read" | "Update" | "Delete";

export interface Privilege {
  entry_type: AppEntryType
  crud: string
}

export interface GetCreateCountInput {
  subject: AgentPubKey
  entryType: MyAppEntryType
}

export interface HasRoleInput {
  subject: AgentPubKey
  roleEh: EntryHash
}

export interface ClaimRoleInput {
  subject: AgentPubKey
  roleEh: EntryHash
  membraneIndex: number
}

export interface MembraneInput {
  subject: AgentPubKey
  membraneEh: EntryHash
}

export enum MembranesEntryType {
	Threshold = 'Threshold',
	Membrane = 'Membrane',
	MembraneCrossedClaim = 'MembraneCrossedClaim',
	Role = 'Role',
	RoleClaim = 'RoleClaim',
	Vouch = 'Vouch',
}
export type MembranesEntryVariantThreshold = {threshold: MembraneThreshold}
export type MembranesEntryVariantMembrane = {membrane: Membrane}
export type MembranesEntryVariantMembraneCrossedClaim = {membraneCrossedClaim: MembraneCrossedClaim}
export type MembranesEntryVariantRole = {role: MembraneRole}
export type MembranesEntryVariantRoleClaim = {roleClaim: RoleClaim}
export type MembranesEntryVariantVouch = {vouch: Vouch}
export type MembranesEntry = 
 | MembranesEntryVariantThreshold | MembranesEntryVariantMembrane | MembranesEntryVariantMembraneCrossedClaim | MembranesEntryVariantRole | MembranesEntryVariantRoleClaim | MembranesEntryVariantVouch;

export interface MembraneZomeProperties {
  progenitors: AgentPubKeyB64[]
}
