/* This file is generated by zits. Do not edit manually */

import {
/** types.ts */
HoloHash,
AgentPubKey,
DnaHash,
WasmHash,
EntryHash,
ActionHash,
AnyDhtHash,
KitsuneAgent,
KitsuneSpace,
HoloHashB64,
AgentPubKeyB64,
DnaHashB64,
WasmHashB64,
EntryHashB64,
ActionHashB64,
AnyDhtHashB64,
InstalledAppId,
Signature,
CellId,
DnaProperties,
RoleName,
Timestamp,
Duration,
HoloHashed,
NetworkInfo,
FetchQueueInfo,
/** hdk/action.ts */
SignedActionHashed,
ActionHashed,
ActionType,
Action,
NewEntryAction,
Dna,
AgentValidationPkg,
InitZomesComplete,
CreateLink,
DeleteLink,
OpenChain,
CloseChain,
Update,
Delete,
Create,
/** hdk/capabilities.ts */
CapSecret,
CapClaim,
ZomeCallCapGrant,
CapAccess,
CapGrant,
GrantedFunctionsType,
///** hdk/countersigning.ts */
//CounterSigningSessionData,
//PreflightRequest,
//CounterSigningSessionTimes,
//ActionBase,
//CounterSigningAgents,
//PreflightBytes,
//Role,
//CountersigningAgentState,
/** hdk/dht-ops.ts */
DhtOpType,
DhtOp,
getDhtOpType,
getDhtOpAction,
getDhtOpEntry,
getDhtOpSignature,
/** hdk/entry.ts */
EntryVisibility,
AppEntryDef,
EntryType,
EntryContent,
Entry,
/** hdk/record.ts */
Record as HcRecord,
RecordEntry as HcRecordEntry,
/** api/admin/types.ts */
InstalledAppInfoStatus,
StemCell,
ProvisionedCell,
ClonedCell,
CellType,
CellInfo,
AppInfo,
MembraneProof,
FunctionName,
ZomeName,
ZomeDefinition,
IntegrityZome,
CoordinatorZome,
DnaDefinition,
ResourceBytes,
ResourceMap,
CellProvisioningStrategy,
CellProvisioning,
DnaVersionSpec,
DnaVersionFlexible,
AppRoleDnaManifest,
AppRoleManifest,
AppManifest,
AppBundle,
AppBundleSource,
NetworkSeed,
ZomeLocation,
   } from '@holochain/client';

import {
/** Common */
DhtOpHashB64,
DhtOpHash,
/** DnaFile */
DnaFile,
DnaDef,
Zomes,
WasmCode,
/** entry-details */
EntryDetails,
RecordDetails,
Details,
DetailsType,
EntryDhtStatus,
/** Validation */
ValidationStatus,
ValidationReceipt,
   } from '@holochain-open-dev/core-types';

/**  */
export interface MembraneCrossedClaim {
  proofAhs: ActionHash[]
  membraneEh: EntryHash
  subject: AgentPubKey
}

/**  */
export interface RoleClaim {
  subject: AgentPubKey
  membraneIndex: number
  roleEh: EntryHash
  membraneClaimEh: EntryHash
}

/**  */
export interface MembraneRole {
  name: string
  privileges: Privilege[]
  enteringMembraneEhs: EntryHash[]
}

/**  */
export interface Membrane {
  thresholdEhs: EntryHash[]
}

export interface MembraneThreshold {
  typeName: string
  data: SerializedBytes
}

/**  */
export interface ThresholdReachedProof {
  thresholdEh: EntryHash
  signedActions: SignedActionHashed[]
}

export type CrudType =
  | {Create: null} | {Read: null} | {Update: null} | {Delete: null};

export interface Privilege {
  entry_def: AppEntryDef
  crud: string
}

export interface HasRoleInput {
  subject: AgentPubKey
  roleEh: EntryHash
}

export interface ClaimRoleInput {
  subject: AgentPubKey
  roleEh: EntryHash
  membraneIndex: number
}

export interface MembraneInput {
  subject: AgentPubKey
  membraneEh: EntryHash
}

export enum MembranesEntryType {
	Threshold = 'Threshold',
	Membrane = 'Membrane',
	Role = 'Role',
	MembraneCrossedClaim = 'MembraneCrossedClaim',
	RoleClaim = 'RoleClaim',
}
export type MembranesEntryVariantThreshold = {Threshold: MembraneThreshold}
export type MembranesEntryVariantMembrane = {Membrane: Membrane}
export type MembranesEntryVariantRole = {Role: MembraneRole}
export type MembranesEntryVariantMembraneCrossedClaim = {MembraneCrossedClaim: MembraneCrossedClaim}
export type MembranesEntryVariantRoleClaim = {RoleClaim: RoleClaim}
export type MembranesEntry = 
 | MembranesEntryVariantThreshold | MembranesEntryVariantMembrane | MembranesEntryVariantRole | MembranesEntryVariantMembraneCrossedClaim | MembranesEntryVariantRoleClaim;

export interface MembraneZomeProperties {
  progenitors: AgentPubKeyB64[]
}

/** Listing all Holochain Path used in this DNA */
export const Roles = "Roles";

export const Membranes = "Membranes";

export const Thresholds = "Thresholds";

export const REMOTE_ENDPOINT = "receive_call";
