/* This file is generated by zits. Do not edit manually */

export enum MembranesUnitEnum {
	Threshold = 'Threshold',
	Membrane = 'Membrane',
	Role = 'Role',
	MembraneCrossedClaim = 'MembraneCrossedClaim',
	RoleClaim = 'RoleClaim',
	ThresholdType = 'ThresholdType',
}

/** List of all Link kinds handled by this Zome */
export enum MembranesLinkType {
	MembranePassport = 'MembranePassport',
	RolePassport = 'RolePassport',
	Role = 'Role',
	Membrane = 'Membrane',
	Threshold = 'Threshold',
}
