/* This file is generated by zits. Do not edit manually */

// @ts-ignore
import {Membranes, REMOTE_ENDPOINT, Roles, Thresholds, CrudType, MembranesEntry, ClaimRoleInput, ClaimThresholdInput, HasRoleInput, Membrane, MembraneCrossedClaim, MembraneInput, MembraneRole, MembraneThreshold, Privilege, RoleClaim, SignedActionHash, ThresholdReachedProof, ThresholdType, } from './membranes.types';
// @ts-ignore
import {
/** api/common.ts */
// @ts-ignore
WebsocketConnectionOptions, WsClientOptions, HolochainError, CloneIdHelper,
/** types.ts */
// @ts-ignore
KitsuneAgent, KitsuneSpace, HoloHashB64, AgentPubKeyB64, DnaHashB64, WasmHashB64, EntryHashB64, ActionHashB64, AnyDhtHashB64, InstalledAppId, Signature, CellId, DnaProperties, RoleName, InstalledCell, Timestamp, Duration, HoloHashed, FetchPoolInfo,
/** hdk/action.ts */
// @ts-ignore
SignedAction, SignedActionHashed, RegisterAgentActivity, ActionHashed, ActionType, Action, NewEntryAction, Dna, AgentValidationPkg, InitZomesComplete, CreateLink, DeleteLink, OpenChain, CloseChain, Update, Delete, Create,
/** hdk/capabilities.ts */
// @ts-ignore
CapSecret, CapClaim, GrantedFunctionsType, GrantedFunctions, ZomeCallCapGrant, CapAccess, CapGrant,
///** hdk/countersigning.ts */
//CounterSigningSessionData,
//PreflightRequest,
//CounterSigningSessionTimes,
//ActionBase,
//CounterSigningAgents,
//PreflightBytes,
//Role,
//CountersigningAgentState,
/** hdk/dht-ops.ts */
// @ts-ignore
ChainOpType, DhtOp, WarrantOp, ChainOp, Warrant, ChainIntegrityWarrant, ValidationType, ActionHashAndSig,
/** hdk/entry.ts */
// @ts-ignore
EntryVisibility, AppEntryDef, EntryType, EntryContent, Entry,
/** hdk/record.ts */
// @ts-ignore
Record as HcRecord, RecordEntry as HcRecordEntry,
/** hdk/link.ts */
//AnyLinkableHash,
// @ts-ignore
ZomeIndex, LinkType, LinkTag, RateWeight, RateBucketId, RateUnits, Link,
/** api/admin/types.ts */
// @ts-ignore
// YamlProperties
Zomes, WasmCode, DisabledAppReason, AppInfoStatus, StemCell, ProvisionedCell, ClonedCell, CellType, CellInfo, AppInfo, MembraneProof, MemproofMap, RoleSettingsMap, RoleSettings, DnaModifiersOpt, DnaModifiers, FunctionName, ZomeName, ZomeDefinition, IntegrityZome, CoordinatorZome, DnaDefinition, ResourceBytes, ResourceMap, CellProvisioningStrategy, CellProvisioning, DnaVersionSpec, DnaVersionFlexible, AppRoleDnaManifest, AppRoleManifest, AppManifest, AppBundle, AppBundleSource, NetworkSeed, AppStatusFilter, AppInterfaceInfo, AgentInfoSigned, ZomeLocation, DnaManifest,
} from '@holochain/client';


/// Simple Hashes
// @ts-ignore
type AgentArray = Uint8Array;
// @ts-ignore
type DnaArray = Uint8Array;
// @ts-ignore
type WasmArray = Uint8Array;
// @ts-ignore
type EntryArray = Uint8Array;
// @ts-ignore
type ActionArray = Uint8Array;
// @ts-ignore
type AnyDhtArray = Uint8Array;
// @ts-ignore
type AnyLinkableArray = Uint8Array;
// @ts-ignore
type ExternalArray = Uint8Array;

// @ts-ignore
import {
/** Common */
// @ts-ignore
DhtOpHashB64, DhtOpHash,
/** DnaFile */
// @ts-ignore
DnaFile, DnaDef,
/** entry-details */
// @ts-ignore
EntryDetails, RecordDetails, Details, DetailsType, EntryDhtStatus,
/** Validation */
// @ts-ignore
ValidationStatus, ValidationReceipt,
} from '@holochain-open-dev/core-types';

import {ZomeProxy} from '@ddd-qc/lit-happ';
import {membranesFunctionNames} from './membranes.fn';
import {MembranesUnitEnum} from './membranes.integrity';
import {MembranesLinkType} from './membranes.integrity';

/**
 *
 */
export class MembranesProxy extends ZomeProxy {
  static override readonly DEFAULT_ZOME_NAME = "membranes";
  static override readonly FN_NAMES = membranesFunctionNames;
  static override readonly ENTRY_TYPES = Object.values(MembranesUnitEnum);
  static override readonly LINK_TYPES = Object.values(MembranesLinkType);
 
  async getAllMembranesDetails(): Promise<[EntryArray, Membrane][]> {
    return this.call('get_all_membranes_details', null);
  }

  async getAllRoles(): Promise<[EntryHashB64, string][]> {
    return this.call('get_all_roles', null);
  }

  async getAllRolesDetails(): Promise<[EntryArray, MembraneRole][]> {
    return this.call('get_all_roles_details', null);
  }

  async getRoleByName(requestedName: string): Promise<MembraneRole | null> {
    return this.call('get_role_by_name', requestedName);
  }

  async getAllThresholdsDetails(): Promise<[EntryArray, MembraneThreshold][]> {
    return this.call('get_all_thresholds_details', null);
  }

  async claimAllMembranes(): Promise<number> {
    return this.call('claim_all_membranes', null);
  }

  async claimMembrane(input: MembraneInput): Promise<EntryHashB64 | null> {
    return this.call('claim_membrane', input);
  }

  async claimRoleWithMembrane(input: ClaimRoleInput): Promise<EntryHashB64 | null> {
    return this.call('claim_role_with_membrane', input);
  }

  async claimRoleByName(roleName: string): Promise<EntryHashB64 | null> {
    return this.call('claim_role_by_name', roleName);
  }

  async claimAllRoles(): Promise<number> {
    return this.call('claim_all_roles', null);
  }

  async getAllThresholds(maybeTypeName: string): Promise<MembraneThreshold[]> {
    return this.call('get_all_thresholds', maybeTypeName);
  }

  async getProof(ah: ActionArray): Promise<ThresholdReachedProof | null> {
    return this.call('get_proof', ah);
  }

  async getThreshold(eh: EntryArray): Promise<MembraneThreshold | null> {
    return this.call('get_threshold', eh);
  }

  async getMembrane(eh: EntryArray): Promise<Membrane | null> {
    return this.call('get_membrane', eh);
  }

  async getRole(eh: EntryArray): Promise<MembraneRole | null> {
    return this.call('get_role', eh);
  }

  async getMembraneCrossedClaim(eh: EntryArray): Promise<MembraneCrossedClaim | null> {
    return this.call('get_membrane_crossed_claim', eh);
  }

  async getMyRoleClaimsDetails(): Promise<[EntryArray, RoleClaim][]> {
    return this.call('get_my_role_claims_details', null);
  }

  async getMyMembraneClaimsDetails(): Promise<[EntryArray, MembraneCrossedClaim][]> {
    return this.call('get_my_membrane_claims_details', null);
  }

  async hasCrossedMembrane(input: MembraneInput): Promise<EntryHashB64 | null> {
    return this.call('has_crossed_membrane', input);
  }

  async dnaInfoHack(): Promise<ZomeName[]> {
    return this.call('dna_info_hack', null);
  }

  async echoAppEntryDef(entryType: AppEntryDef): Promise<void> {
    return this.call('echo_app_entry_def', entryType);
  }

  async publishThreshold(threshold: MembraneThreshold): Promise<EntryArray> {
    return this.call('publish_threshold', threshold);
  }

  async publishMembrane(membrane: Membrane): Promise<EntryArray> {
    return this.call('publish_membrane', membrane);
  }

  async publishRole(role: MembraneRole): Promise<EntryArray> {
    return this.call('publish_role', role);
  }

  async publishRoleClaim(claim: RoleClaim): Promise<EntryArray> {
    return this.call('publish_RoleClaim', claim);
  }

  async publishMembraneCrossedClaim(claim: MembraneCrossedClaim): Promise<EntryArray> {
    return this.call('publish_MembraneCrossedClaim', claim);
  }

  async registerThresholdType(tt: ThresholdType): Promise<ActionArray> {
    return this.call('register_threshold_type', tt);
  }

  async getAllRegisteredThresholdTypes(): Promise<ThresholdType[]> {
    return this.call('get_all_registered_threshold_types', null);
  }

  async getZomeForThreshold(typeName: string): Promise<string> {
    return this.call('get_zome_for_threshold', typeName);
  }

  async getRoleWithName(name: string): Promise<[EntryArray, MembraneRole] | null> {
    return this.call('get_role_with_name', name);
  }

  async hasRole(input: HasRoleInput): Promise<SignedActionHashed | null> {
    return this.call('has_role', input);
  }

  async doIHaveRole(roleEh: EntryHashB64): Promise<EntryHashB64 | null> {
    return this.call('do_i_have_role', roleEh);
  }
}
