/* This file is generated by zits. Do not edit manually */

import {ZomeName, FunctionName} from '@holochain/client';


/** Array of all zome function names in "progenitor" */
export const progenitorFunctionNames: FunctionName[] = [
	"entry_defs", 
	"get_zome_info", 
	"get_dna_info",


	"claim_threshold_Progenitor",];


/** Generate tuple array of function names with given zomeName */
export function generateProgenitorZomeFunctionsArray(zomeName: ZomeName): [ZomeName, FunctionName][] {
   const fns: [ZomeName, FunctionName][] = [];
   for (const fn of progenitorFunctionNames) {
      fns.push([zomeName, fn]);
   }
   return fns;
}


/** Tuple array of all zome function names with default zome name "zThreshold_Progenitor" */
export const progenitorZomeFunctions: [ZomeName, FunctionName][] = generateProgenitorZomeFunctionsArray("zThreshold_Progenitor");
