/* This file is generated by zits. Do not edit manually */

export enum VouchUnitEnum {
	VouchProof = 'VouchProof',
	Vouch = 'Vouch',
}

/** List of all Link kinds handled by this Zome */
export enum VouchLinkType {
	VouchCreated = 'VouchCreated',
	VouchEmitted = 'VouchEmitted',
	VouchReceived = 'VouchReceived',
}
